
const profiles = [
  {
    img: "../asset/image/gf1.png",
    title: "Deep Learning",
    name: "Deep Learning Basics",
    bgColor: '#ff7043',
  },
  {
    img: "../asset/image/gf2.png",
    title: "Deep Learning",
    name: "TensorFlow Projects",
    bgColor: '#29b6f6',
  },
  {
    img: "../asset/image/gf3.png",
    title: "Deep Learning",
    name: "Convolutional Neural Networks",
    bgColor: '#ab47bc',
  },
  {
    img: "../asset/image/gf4.png",
    title: "Machine Learning",
    name: "ML Fundamentals",
    bgColor: '#66bb6a',
  },
  {
    img: "../asset/image/gf5.png",
    title: "Machine Learning",
    name: "Scikit-learn Projects",
    bgColor: '#ffa726',
  },
  {
    img: "../asset/image/gf6.png",
    title: "Machine Learning",
    name: "Feature Engineering",
    bgColor: '#5c6bc0',
  },
  {
    img: "../asset/image/gf7.png",
    title: "Cybersecurity",
    name: "Manual Testing",
    bgColor: '#ef5350',
  },
  {
    img: "../asset/image/gf8.png",
    title: "Cybersecurity",
    name: "Ethical Hacking",
    bgColor: '#ec407a',
  },
  {
    img: "../asset/image/gf9.png",
    title: "Cybersecurity",
    name: "Network Security",
    bgColor: '#26c6da',
  },
  {
    img: "../asset/image/gf10.png",
    title: "Testing",
    name: "Manual Testing",
    bgColor: '#8d6e63',
  },
  {
    img: "../asset/image/gf11.png",
    title: "Testing",
    name: "Automation Testing",
    bgColor: '#ffca28',
  },
  {
    img: "../asset/image/gf35.png",
    title: "Testing",
    name: "API Testing with Postman",
    bgColor: '#7e57c2',
  },
  {
    img: "../asset/image/gf13.png",
    title: "IoT",
    name: "IoT Fundamentals",
    bgColor: '#26a69a',
  },
  {
    img: "../asset/image/gf14.png",
    title: "AI",
    name: "Machine Learning",
    bgColor: '#42a5f5',
  },
  {
    img: "../asset/image/gf15.png",
    title: "AI",
    name: "Deep Learning",
    bgColor: '#ef5350',
  },
  {
    img: "../asset/image/gf16.png",
    title: "AI",
    name: "Natural Language Processing",
    bgColor: '#66bb6a',
  },
  {
    img: "../asset/image/gf17.png",
    title: "AI",
    name: "Computer Vision",
    bgColor: '#ffa726',
  },
  {
    img: "../asset/image/gf18.png",
    title: "AI",
    name: "Generative AI",
    bgColor: '#ab47bc',
  },
  {
    img: "../asset/image/gf19.png",
    title: "AI",
    name: "AI Tools & Platforms",
    bgColor: '#78909c',
  },
  {
    img: "../asset/image/gf20.png",
    title: "Digital Marketing",
    name: "SEO Mastery",
    bgColor: '#f06292',
  },
  {
    img: "../asset/image/gf25.png",
    title: "Digital Marketing",
    name: "Google Ads (SEM)",
    bgColor: '#4db6ac',
  },
  {
    img: "../asset/image/gf21.png",
    title: "Digital Marketing",
    name: "Social Media Marketing",
    bgColor: '#ff7043',
  },
  {
    img: "../asset/image/gf22.png",
    title: "Digital Marketing",
    name: "Email Marketing",
    bgColor: '#7986cb',
  },
  {
    img: "../asset/image/gf23.png",
    title: "Digital Marketing",
    name: "Google Analytics",
    bgColor: '#9575cd',
  },
  {
    img: "../asset/image/gf24.png",
    title: "Digital Marketing",
    name: "Content Marketing",
    bgColor: '#90a4ae',
  },
  {
    img: "../asset/image/gf25.png",
    title: "Web Fullstack Development",
    name: "MERN Stack",
    bgColor: '#4fc3f7',
  },
  {
    img: "../asset/image/gf26.png",
    title: "UI/UX Design",
    name: "Figma UI Design",
    bgColor: '#ff8a65',
  },
  {
    img: "../asset/image/gf27.png",
    title: "UI/UX Design",
    name: "Adobe XD Prototyping",
    bgColor: '#a1887f',
  },
  {
    img: "../asset/image/gf28.png",
    title: "UI/UX Design",
    name: "Wireframing Basics",
    bgColor: '#ba68c8',
  },
  {
    img: "../asset/image/gf29.png",
    title: "UI/UX Design",
    name: "Interactive Prototyping",
    bgColor: '#4dd0e1',
  },
  {
    img: "../asset/image/gf30.png",
    title: "UI/UX Design",
    name: "User Research",
    bgColor: '#ce93d8',
  },
  {
    img: "../asset/image/gf31.png",
    title: "UI/UX Design",
    name: "Design Systems",
    bgColor: '#7986cb',
  },
  {
    img: "../asset/image/gf32.png",
    title: "Web Fullstack Development",
    name: "MEAN Stack",
    bgColor: '#4db6ac',
  },
  {
    img: "../asset/image/gf33.png",
    title: "Web Fullstack Development",
    name: "Python Fullstack",
    bgColor: '#fbc02d',
  },
  {
    img: "../asset/image/gf34.png",
    title: "Web Fullstack Development",
    name: "Java Fullstack",
    bgColor: '#e57373',
  },
  {
    img: "../asset/image/gf35.png",
    title: "Mobile Fullstack Development",
    name: "React Native + Node.js",
    bgColor: '#81d4fa',
  },
  {
    img: "../asset/image/gf36.png",
    title: "Mobile Fullstack Development",
    name: "Kivy + FastAPI",
    bgColor: '#aed581',
  },
  {
    img: "../asset/image/gf37.png",
    title: "Mobile Fullstack Development",
    name: "Android (Java) + Spring Boot",
    bgColor: '#ff8a65',
  },
  {
    img: "../asset/image/gf38.png",
    title: "Mobile Development",
    name: "React Native",
    bgColor: '#7986cb',
  },
  {
    img: "../asset/image/gf39.png",
    title: "Mobile Development",
    name: "Ionic",
    bgColor: '#f06292',
  },
  {
    img: "../asset/image/gf40.png",
    title: "Mobile Development",
    name: "Flutter",
    bgColor: '#64b5f6',
  },
  {
    img: "../asset/image/gf41.png",
    title: "Mobile Development",
    name: "Kivy",
    bgColor: '#4db6ac',
  },
  {
    img: "../asset/image/gf42.png",
    title: "Machine Learning",
    name: "Steve Jobs",
    bgColor: '#b39ddb',
  },
  {
    img: "../asset/image/gf43.png",
    title: "Web Development",
    name: "Html,Css,Js",
    bgColor: '#4fc3f7',
  },
  {
    img: "../asset/image/gf44.png",
    title: "Web Development",
    name: "React",
    bgColor: '#81d4fa',
  },
  {
    img: "../asset/image/gf45.png",
    title: "Web Development",
    name: "Angular",
    bgColor: '#ef5350',
  },
  {
    img: "../asset/image/gf46.png",
    title: "Web Development",
    name: "Bootstrap / Tailwind CSS",
    bgColor: '#9575cd',
  },
  {
    img: "../asset/image/gf47.png",
    title: "Backend",
    name: "Node.js",
    bgColor: '#66bb6a',
  },
  {
    img: "../asset/image/gf48.png",
    title: "Backend",
    name: "Express.js",
    bgColor: '#ffa726',
  },
  {
    img: "../asset/image/gf49.png",
    title: "Backend",
    name: "NestJS",
    bgColor: '#ec407a',
  },
  {
    img: "../asset/image/gf50.png",
    title: "Backend",
    name: "Django",
    bgColor: '#26c6da',
  },
  {
    img: "../asset/image/gf51.png",
    title: "Backend",
    name: "Flask",
    bgColor: '#78909c',
  },
  {
    img: "../asset/image/gf7.png",
    title: "Backend",
    name: "FastAPI",
    bgColor: '#26a69a',
  },
  {
    img: "../asset/image/gf18.png",
    title: "Backend",
    name: "Spring Boot",
    bgColor: '#8bc34a',
  },
];

export default profiles